name: CI Validation
on:
  - push

jobs:
  build_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Leverage Cache
        uses: Swatinem/rust-cache@v1
      - name: Build Library
        uses: actions-rs/cargo@v1
        with:
          command: build
        run: cargo build
      - name: Run Unit Tests
        uses: actions-rs/cargo@v1
        with:
          command: test